# Generated by Django 5.1.2 on 2026-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_student_created_at_student_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
